version: "3"
services:
  openresty:
    image: openresty/openresty:1.25.3.1-1-alpine-fat
    container_name: 'openresty'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './log:/var/log/openresty'
      - './conf.d:/etc/nginx/conf.d'
      - './nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './data:/data'
      - './cert:/usr/local/openresty/nginx/cert'
